"""Initial schema with staged registration system

Revision ID: 0c1a76b3cd49
Revises: 
Create Date: 2025-08-10 12:06:08.848975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1a76b3cd49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_registrations_created_at'), 'pending_registrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_registrations_email'), 'pending_registrations', ['email'], unique=False)
    op.create_index(op.f('ix_pending_registrations_id'), 'pending_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_pending_registrations_username'), 'pending_registrations', ['username'], unique=False)
    op.create_index(op.f('ix_pending_registrations_verification_token'), 'pending_registrations', ['verification_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_registrations_verification_token'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_username'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_id'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_email'), table_name='pending_registrations')
    op.drop_index(op.f('ix_pending_registrations_created_at'), table_name='pending_registrations')
    op.drop_table('pending_registrations')
    # ### end Alembic commands ###
