"""Remove email_verified field - all users verified by definition with staged registration

Revision ID: 726e9c759cfe
Revises: 64e9db92cef4
Create Date: 2025-08-10 21:12:00.854210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726e9c759cfe'
down_revision: Union[str, None] = '64e9db92cef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
